print("Thou sacred mount, on whose pale forehead now")
print("A desert quiet reigneth, ere the soul")
print("Goes up to sit in meditation there,")
print("She shall put off this world, with all its cares")
print("And fading glory, to commune alone")
print("With God, and with herself, on themes divine!")
print("Thought, on swift wing, darts o'er the dubious waves")
print("Where things promiscuous, by three thousand years,")
print("Are swept together in one shadowy deep,")
print("And rests on Olivet!")
print("Marcus Jones Jr.")
