VOCAB
NOT
AND
Logic Operator
OR
ASC
DESC
ORDER BY

SQL
1.
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%e%' AND LAST_NAME LIKE '%i%'

2.
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID NOT IN(80) AND SALARY > 6000

3.
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE'D%' AND LAST_NAME LIKE '%a%' AND LAST_NAME LIKE '%E%'

4.
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE HIRE_DATE > '1998-MAY' AND HIRE_DATE < '1999-JUN' AND SALARY < 8000 AND LAST_NAME LIKE '%en%'

5.
SELECT FIRST_NAME + ' ' + LAST_NAME AS "Full Name", EMAIL
FROM EMPLOYEES
WHERE HIRE_DATE <'1996-MAR-31' AND HIRE_DATE > '1995-DEC-31' AND SALARY > 9000 AND COMMISSION_PCT IS NULL

6.
SELECT JOB_TITLE, JOB_ID
FROM JOBS
ORDER BY JOB_TITLE

7.
SELECT FIRST_NAME , LAST_NAME , DEPARTMENT_ID
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID DESC, LAST_NAME ASC;

General Questions
1.
c. NOT, AND, OR

2.
e. Selection

3.
c. ORDER BY

4. 
c. Parentheses can be used to override the rules pf precedence

5.
c. To select last names without duplicates

6.
b. Jane Hendricks, sales manager, salary 15500

7.
410